### ISSUE TITLE
Autoremove deleted emotes

### ISSUE THREAD

**Issue by Elementalmp4** [Gerald-Development/Barista-Gerald#91]
Create a system to automatically remove emotes that do not exist anymore. This may need to be done with a monthly db audit or something, or checked on each Nitrolite message

**Comment by Montori** [comment]
We can implement a DelayedTask system (also mentioned in #105) to do a weekly clean up of the emotes. This DelayedTask will run through all of the saved emotes and check against discord if they exist. We may need a different approach tho since I don't think that discord accepts our 4000 requests per milliseconds

**Comment by Elementalmp4** [comment]
I thought about a solution and I think I have one

We can modify the methods which supply the NitroliteEmote object (which all our emote-based modules use for a standardised format) and when an emote is asked for, we can check to see if it exists by checking the response code of its CDN URL. If there is no emote, it will be immediately deleted, and if searching by name, then we will search for that name again until one is found or there are no by that name left, at which point a filler name will be returned which says **Emote No Longer Exists** (or similar)
